# Generated by Django 4.0.4 on 2022-05-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dirRecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dirRecord.directoryrecords')),
            ],
        ),
    ]
