# Generated by Django 4.0.4 on 2022-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirRecord', '0002_dirfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirfiles',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
