# Generated by Django 4.0.4 on 2022-05-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirRecord', '0004_alter_dirfiles_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryrecords',
            name='monitor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
